using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VeloSpace.DTOs.LaunchProvidersDTOS;
using VeloSpace.Services.LaunchProvidersServices;

namespace VeloSpace.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class LaunchProviderController : ControllerBase
{
    private readonly ILaunchProvidersService _launchProvidersService;

    public LaunchProviderController(ILaunchProvidersService launchProvidersService)
    {
        _launchProvidersService = launchProvidersService;
    }

    /// <summary>
    /// Returns all registered Launch Providers.
    /// </summary>
    /// <remarks>
    /// Non-paginated endpoint. Returns the complete collection of Launch Providers with their linked user account data.
    ///
    /// Possible status codes:
    /// - 200 OK: collection returned successfully
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while retrieving data
    /// </remarks>
    /// <returns>Collection of Launch Providers with user account information.</returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            var getAllLaunchProviders = await _launchProvidersService.GetAllAsync();

            return Ok(new { items = getAllLaunchProviders });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Launch Providers",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Gets a specific Launch Provider by ID.
    /// </summary>
    /// <param name="id">Launch Provider ID.</param>
    /// <remarks>
    /// Endpoint that returns a specific Launch Provider with its linked user account data.
    ///
    /// Possible status codes:
    /// - 200 OK: Launch Provider found and returned in the response body
    /// - 404 Not Found: no Launch Provider with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected server error
    /// </remarks>
    /// <returns>Resource containing Launch Provider and user account information.</returns>
    [HttpGet("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetById(long id)
    {
        try
        {
            var getLaunchProviderId = await _launchProvidersService.GetByIdAsync(id);

            return Ok(getLaunchProviderId);
        }
        catch (LaunchProvidersService.NotFoundException ntex)
        {
            return NotFound(ntex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Launch Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Registers a new Launch Provider in the database.
    /// </summary>
    /// <param name="launchProviderRequestDto">Data of the Launch Provider and user account to be created.</param>
    /// <remarks>
    /// Public endpoint used to create a Launch Provider and its linked user account.
    ///
    /// The user account is created first. Then the generated <c>userAccountId</c> is used to link the Launch Provider to that account.
    ///
    /// Automatically Generated Fields:
    /// - <c>launchProviderId</c>: generated by the database
    /// - <c>userAccountId</c>: generated by the database
    /// - <c>hashedPassword</c>: the plain password received in the request is hashed before being saved
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "launchProviderDto": {
    ///         "corporateName": "Space Launch Brasil LTDA",
    ///         "cnpj": "12345678912345"
    ///     },
    ///     "userAccountDto": {
    ///         "email": "launch.provider@email.com",
    ///         "hashedPassword": "Senha123",
    ///         "phone": "11999998888",
    ///         "userRoleId": 2
    ///     }
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 201 Created: Launch Provider registered successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 409 Conflict: email, CNPJ, or other unique information already registered
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while registering the Launch Provider
    /// </remarks>
    /// <returns>Success message after creating the Launch Provider.</returns>
    [AllowAnonymous]
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> AddLaunchProvider([FromBody] LaunchProviderRequestDTO launchProviderRequestDto)
    {
        try
        {
            await _launchProvidersService.AddAsync(launchProviderRequestDto);

            return Created("", new { message = "Launch Provider added successfully" });
        }
        catch (LaunchProvidersService.ConflictException ex)
        {
            return Conflict(ex.Message);
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when adding the Launch Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Updates the information of an existing Launch Provider.
    /// </summary>
    /// <param name="id">Launch Provider ID.</param>
    /// <param name="launchProviderDto">Launch Provider data to be updated.</param>
    /// <remarks>
    /// Endpoint that updates only the Launch Provider registration data.
    /// It does not update the linked user account data.
    ///
    /// The Launch Provider ID is required only in the route parameter.
    /// If the same information is sent in the request body, the route parameter is used as the main identifier.
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "corporateName": "Space Launch Brasil Atualizada LTDA",
    ///     "cnpj": "98765432112345"
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: Launch Provider updated successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 404 Not Found: no Launch Provider with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while updating the Launch Provider
    /// </remarks>
    /// <returns>Success message after updating the Launch Provider.</returns>
    [HttpPut("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateLaunchProvider(long id, [FromBody] LaunchProviderDTO launchProviderDto)
    {
        try
        {
            await _launchProvidersService.UpdateAsync(id, launchProviderDto);

            return Ok(new { message = $"Launch Provider with id {id} updated successfully" });
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (LaunchProvidersService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when updating the Launch Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Deletes a Launch Provider by ID.
    /// </summary>
    /// <param name="id">Launch Provider ID.</param>
    /// <remarks>
    /// Endpoint used to delete a Launch Provider registration from the database.
    ///
    /// According to the service rule, the linked user account may also be deleted after deleting the Launch Provider.
    ///
    /// Possible status codes:
    /// - 200 OK: Launch Provider deleted successfully
    /// - 404 Not Found: no Launch Provider with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while deleting the Launch Provider
    /// </remarks>
    /// <returns>Success message after deleting the Launch Provider.</returns>
    [HttpDelete("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> DeleteLaunchProvider(long id)
    {
        try
        {
            await _launchProvidersService.DeleteAsync(id);

            return Ok(new { message = $"Launch Provider with id {id} deleted" });
        }
        catch (LaunchProvidersService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when deleting the Launch Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Searches Launch Providers with optional filters, pagination, and sorting.
    /// </summary>
    /// <param name="corporateName">Corporate name for optional filtering.</param>
    /// <param name="cnpj">CNPJ for optional filtering.</param>
    /// <param name="page">Page number. Default: 1, minimum: 1.</param>
    /// <param name="pageSize">Page size. Default: 10, maximum according to the application rule.</param>
    /// <param name="sortBy">Sorting field. Default: <c>launchProviderId</c>.</param>
    /// <param name="sortDir">Sorting direction: <c>asc</c> or <c>desc</c>.</param>
    /// <remarks>
    /// Returns Launch Providers matching the search criteria.
    ///
    /// Example request:
    /// <code>
    /// GET /api/LaunchProvider/search?corporateName=Space&amp;cnpj=12345678912345&amp;page=1&amp;pageSize=10&amp;sortBy=launchProviderId&amp;sortDir=asc
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: results returned successfully. The list may be empty
    /// - 400 Bad Request: invalid filter, pagination, or sorting parameters
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while performing the search
    /// </remarks>
    /// <returns>Paginated collection of Launch Providers with pagination information.</returns>
    [HttpGet("search")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> SearchLaunchProvider(
        [FromQuery] string? corporateName,
        [FromQuery] string? cnpj,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 10,
        [FromQuery] string sortBy = "launchProviderId",
        [FromQuery] string sortDir = "asc"
    )
    {
        try
        {
            var result = await _launchProvidersService.SearchAsync(corporateName, cnpj, page, pageSize, sortBy, sortDir);

            return Ok(new { Items = result.Items, PageInfo = result.PageInfo });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching the Launch Provider",
                details = ex.Message
            });
        }
    }
}