using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VeloSpace.DTOs.OperatorDTOS;
using VeloSpace.Services.OperatorServices;

namespace VeloSpace.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class OperatorController : ControllerBase
{
    private readonly IOperatorService _operatorService;

    public OperatorController(IOperatorService operatorService)
    {
        _operatorService = operatorService;
    }

    /// <summary>
    /// Returns all registered Operators.
    /// </summary>
    /// <remarks>
    /// Non-paginated endpoint. Returns the complete collection of Operators with their linked user account data.
    ///
    /// Possible status codes:
    /// - 200 OK: collection returned successfully
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while retrieving data
    /// </remarks>
    /// <returns>Collection of Operators with user account information.</returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            var getAllOperators = await _operatorService.GetAllAsync();

            return Ok(new { items = getAllOperators });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Operators",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Gets a specific Operator by ID.
    /// </summary>
    /// <param name="id">Operator ID.</param>
    /// <remarks>
    /// Endpoint that returns a specific Operator with its linked user account data.
    ///
    /// Possible status codes:
    /// - 200 OK: Operator found and returned in the response body
    /// - 404 Not Found: no Operator with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected server error
    /// </remarks>
    /// <returns>Resource containing Operator and user account information.</returns>
    [HttpGet("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetById(long id)
    {
        try
        {
            var getOperatorId = await _operatorService.GetByIdAsync(id);

            return Ok(getOperatorId);
        }
        catch (OperatorService.NotFoundException ntex)
        {
            return NotFound(ntex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Operator",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Registers a new Operator in the database.
    /// </summary>
    /// <param name="operatorRequestDto">Data of the Operator and user account to be created.</param>
    /// <remarks>
    /// Public endpoint used to create an Operator and its linked user account.
    ///
    /// The user account is created first. Then the generated <c>userAccountId</c> must be used to link the Operator to that account.
    ///
    /// Required relationships:
    /// - <c>operatorStatusId</c>: must reference an existing Operator Status
    /// - <c>launchProviderId</c>: must reference an existing Launch Provider
    /// - <c>userRoleId</c>: must reference an existing User Role
    ///
    /// Automatically Generated Fields:
    /// - <c>operatorId</c>: generated by the database
    /// - <c>userAccountId</c>: generated by the database
    /// - <c>hashedPassword</c>: the plain password received in the request is hashed before being saved
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "operatorDto": {
    ///         "name": "Carlos Operador",
    ///         "cpf": 12345678910,
    ///         "operatorStatusId": 1,
    ///         "launchProviderId": 1
    ///     },
    ///     "userAccountDto": {
    ///         "email": "carlos.operador@email.com",
    ///         "hashedPassword": "Senha123",
    ///         "phone": "11999998888",
    ///         "userRoleId": 3
    ///     }
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 201 Created: Operator registered successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 409 Conflict: email, CPF, or other unique information already registered
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while registering the Operator
    /// </remarks>
    /// <returns>Success message after creating the Operator.</returns>
    [AllowAnonymous]
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> AddOperator([FromBody] OperatorRequestDTO operatorRequestDto)
    {
        try
        {
            await _operatorService.AddAsync(operatorRequestDto);

            return Created("", new { message = "Operator added successfully" });
        }
        catch (OperatorService.ConflictException ex)
        {
            return Conflict(ex.Message);
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when adding the Operator",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Updates the information of an existing Operator.
    /// </summary>
    /// <param name="id">Operator ID.</param>
    /// <param name="operatorDto">Operator data to be updated.</param>
    /// <remarks>
    /// Endpoint that updates only the Operator registration data.
    /// It does not update the linked user account data.
    ///
    /// The Operator ID is required only in the route parameter.
    /// If the same information is sent in the request body, the route parameter is used as the main identifier.
    ///
    /// Required relationships:
    /// - <c>operatorStatusId</c>: must reference an existing Operator Status
    /// - <c>launchProviderId</c>: must reference an existing Launch Provider
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "name": "Carlos Operador Atualizado",
    ///     "cpf": 12345678910,
    ///     "operatorStatusId": 1,
    ///     "launchProviderId": 1
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: Operator updated successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 404 Not Found: no Operator with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while updating the Operator
    /// </remarks>
    /// <returns>Success message after updating the Operator.</returns>
    [HttpPut("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateOperator(long id, [FromBody] OperatorDTO operatorDto)
    {
        try
        {
            await _operatorService.UpdateAsync(id, operatorDto);

            return Ok(new { message = $"Operator with id {id} updated successfully" });
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (OperatorService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when updating the Operator",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Deletes an Operator by ID.
    /// </summary>
    /// <param name="id">Operator ID.</param>
    /// <remarks>
    /// Endpoint used to delete an Operator registration from the database.
    ///
    /// According to the service rule, the linked user account may also be deleted after deleting the Operator.
    ///
    /// Possible status codes:
    /// - 200 OK: Operator deleted successfully
    /// - 404 Not Found: no Operator with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while deleting the Operator
    /// </remarks>
    /// <returns>Success message after deleting the Operator.</returns>
    [HttpDelete("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> DeleteOperator(long id)
    {
        try
        {
            await _operatorService.DeleteAsync(id);

            return Ok(new { message = $"Operator with id {id} deleted" });
        }
        catch (OperatorService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when deleting the Operator",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Searches Operators with optional filters, pagination, and sorting.
    /// </summary>
    /// <param name="name">Operator name for optional filtering.</param>
    /// <param name="cpf">Operator CPF for optional filtering.</param>
    /// <param name="operatorStatusId">Operator status ID for optional filtering.</param>
    /// <param name="launchProviderId">Launch Provider ID for optional filtering.</param>
    /// <param name="page">Page number. Default: 1, minimum: 1.</param>
    /// <param name="pageSize">Page size. Default: 10, maximum according to the application rule.</param>
    /// <param name="sortBy">Sorting field. Default: <c>operatorId</c>.</param>
    /// <param name="sortDir">Sorting direction: <c>asc</c> or <c>desc</c>.</param>
    /// <remarks>
    /// Returns Operators matching the search criteria.
    ///
    /// Example request:
    /// <code>
    /// GET /api/Operator/search?name=Carlos&amp;cpf=12345678910&amp;operatorStatusId=1&amp;launchProviderId=1&amp;page=1&amp;pageSize=10&amp;sortBy=operatorId&amp;sortDir=asc
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: results returned successfully. The list may be empty
    /// - 400 Bad Request: invalid filter, pagination, or sorting parameters
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while performing the search
    /// </remarks>
    /// <returns>Paginated collection of Operators with pagination information.</returns>
    [HttpGet("search")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> SearchOperator(
        [FromQuery] string? name,
        [FromQuery] int? cpf,
        [FromQuery] long? operatorStatusId,
        [FromQuery] long? launchProviderId,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 10,
        [FromQuery] string sortBy = "operatorId",
        [FromQuery] string sortDir = "asc"
    )
    {
        try
        {
            var result = await _operatorService.SearchAsync(name, cpf, operatorStatusId, launchProviderId, page, pageSize, sortBy, sortDir);

            return Ok(new { Items = result.Items, PageInfo = result.PageInfo });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching the Operators",
                details = ex.Message
            });
        }
    }
}