using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VeloSpace.DTOs.RocketDTOS;
using VeloSpace.Services.RocketServices;

namespace VeloSpace.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class RocketController : ControllerBase
{
    private readonly IRocketService _rocketService;

    public RocketController(IRocketService rocketService)
    {
        _rocketService = rocketService;
    }

    /// <summary>
    /// Returns all registered Rockets.
    /// </summary>
    /// <remarks>
    /// Non-paginated endpoint. Returns the complete collection of Rockets.
    ///
    /// Possible status codes:
    /// - 200 OK: collection returned successfully
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while retrieving data
    /// </remarks>
    /// <returns>Collection of Rockets.</returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            var getAllRockets = await _rocketService.GetAllAsync();

            return Ok(new { items = getAllRockets });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Rockets",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Gets a specific Rocket by ID.
    /// </summary>
    /// <param name="id">Rocket ID.</param>
    /// <remarks>
    /// Endpoint that returns a specific Rocket by its identifier.
    ///
    /// Possible status codes:
    /// - 200 OK: Rocket found and returned in the response body
    /// - 404 Not Found: no Rocket with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected server error
    /// </remarks>
    /// <returns>Resource containing Rocket information.</returns>
    [HttpGet("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetById(long id)
    {
        try
        {
            var getRocketId = await _rocketService.GetByIdAsync(id);

            return Ok(getRocketId);
        }
        catch (RocketService.NotFoundException ntex)
        {
            return NotFound(ntex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Rocket",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Registers a new Rocket in the database.
    /// </summary>
    /// <param name="rocketDto">Data of the Rocket to be created.</param>
    /// <remarks>
    /// Endpoint used to create a new Rocket.
    ///
    /// The <c>launchDate</c> is automatically generated by the service using the current date and time when the Rocket is registered.
    ///
    /// Required relationships:
    /// - <c>rocketStatusId</c>: must reference an existing Rocket Status
    ///
    /// Automatically Generated Fields:
    /// - <c>rocketId</c>: generated by the database
    /// - <c>launchDate</c>: generated by the application at registration time
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "name": "Falcon Test",
    ///     "capacityHeight": 70,
    ///     "capacityWidth": 12,
    ///     "capacityLength": 30,
    ///     "capacityWeight": 500,
    ///     "rocketStatusId": 1
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 201 Created: Rocket registered successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while registering the Rocket
    /// </remarks>
    /// <returns>Success message after creating the Rocket.</returns>
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> AddRocket([FromBody] RocketDTO rocketDto)
    {
        try
        {
            await _rocketService.AddAsync(rocketDto);

            return Created("", new { message = "Rocket added successfully" });
        }
        catch (RocketService.ConflictException ex)
        {
            return Conflict(ex.Message);
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when adding the Rocket",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Updates the information of an existing Rocket.
    /// </summary>
    /// <param name="id">Rocket ID.</param>
    /// <param name="rocketDto">Rocket data to be updated.</param>
    /// <remarks>
    /// Endpoint that updates an existing Rocket registration.
    ///
    /// The Rocket ID is required only in the route parameter.
    /// If the same information is sent in the request body, the route parameter is used as the main identifier.
    ///
    /// The <c>launchDate</c> should not be updated by this endpoint if it represents the registration date.
    ///
    /// Required relationships:
    /// - <c>rocketStatusId</c>: must reference an existing Rocket Status
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "name": "Falcon Test Atualizado",
    ///     "capacityHeight": 75,
    ///     "capacityWidth": 13,
    ///     "capacityLength": 32,
    ///     "capacityWeight": 550,
    ///     "rocketStatusId": 1
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: Rocket updated successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 404 Not Found: no Rocket with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while updating the Rocket
    /// </remarks>
    /// <returns>Success message after updating the Rocket.</returns>
    [HttpPut("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateRocket(long id, [FromBody] RocketDTO rocketDto)
    {
        try
        {
            await _rocketService.UpdateAsync(id, rocketDto);

            return Ok(new { message = $"Rocket with id {id} updated successfully" });
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (RocketService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when updating the Rocket",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Deletes a Rocket by ID.
    /// </summary>
    /// <param name="id">Rocket ID.</param>
    /// <remarks>
    /// Endpoint used to delete a Rocket registration from the database.
    ///
    /// Possible status codes:
    /// - 200 OK: Rocket deleted successfully
    /// - 404 Not Found: no Rocket with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while deleting the Rocket
    /// </remarks>
    /// <returns>Success message after deleting the Rocket.</returns>
    [HttpDelete("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> DeleteRocket(long id)
    {
        try
        {
            await _rocketService.DeleteAsync(id);

            return Ok(new { message = $"Rocket with id {id} deleted" });
        }
        catch (RocketService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when deleting the Rocket",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Searches Rockets with optional filters, pagination, and sorting.
    /// </summary>
    /// <param name="name">Rocket name for optional filtering.</param>
    /// <param name="capacityHeight">Rocket capacity height for optional filtering.</param>
    /// <param name="capacityWidth">Rocket capacity width for optional filtering.</param>
    /// <param name="capacityLength">Rocket capacity length for optional filtering.</param>
    /// <param name="capacityWeight">Rocket capacity weight for optional filtering.</param>
    /// <param name="rocketStatusId">Rocket status ID for optional filtering.</param>
    /// <param name="page">Page number. Default: 1, minimum: 1.</param>
    /// <param name="pageSize">Page size. Default: 10, maximum according to the application rule.</param>
    /// <param name="sortBy">Sorting field. Default: <c>rocketId</c>.</param>
    /// <param name="sortDir">Sorting direction: <c>asc</c> or <c>desc</c>.</param>
    /// <remarks>
    /// Returns Rockets matching the search criteria.
    ///
    /// Example request:
    /// <code>
    /// GET /api/Rocket/search?name=Falcon&amp;capacityHeight=70&amp;capacityWidth=12&amp;capacityLength=30&amp;capacityWeight=500&amp;rocketStatusId=1&amp;page=1&amp;pageSize=10&amp;sortBy=rocketId&amp;sortDir=asc
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: results returned successfully. The list may be empty
    /// - 400 Bad Request: invalid filter, pagination, or sorting parameters
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while performing the search
    /// </remarks>
    /// <returns>Paginated collection of Rockets with pagination information.</returns>
    [HttpGet("search")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> SearchRocket(
        [FromQuery] string? name,
        [FromQuery] int? capacityHeight,
        [FromQuery] int? capacityWidth,
        [FromQuery] int? capacityLength,
        [FromQuery] int? capacityWeight,
        [FromQuery] long? rocketStatusId,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 10,
        [FromQuery] string sortBy = "rocketId",
        [FromQuery] string sortDir = "asc"
    )
    {
        try
        {
            var result = await _rocketService.SearchAsync(name, capacityHeight, capacityWidth, capacityLength, capacityWeight, rocketStatusId, page, pageSize, sortBy, sortDir);

            return Ok(new { Items = result.Items, PageInfo = result.PageInfo });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching the Rockets",
                details = ex.Message
            });
        }
    }
}