using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VeloSpace.DTOs.Shippers;
using VeloSpace.Services.ShippersServices;

namespace VeloSpace.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class ShipperController : ControllerBase
{
    private readonly IShipperService _shipperService;

    public ShipperController(IShipperService shipperService)
    {
        _shipperService = shipperService;
    }

    /// <summary>
    /// Returns all registered Shippers.
    /// </summary>
    /// <remarks>
    /// Non-paginated endpoint. Returns the complete collection of Shippers with their linked user account data.
    ///
    /// Possible status codes:
    /// - 200 OK: collection returned successfully
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while retrieving data
    /// </remarks>
    /// <returns>Collection of Shippers with user account information.</returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            var getAllShippers = await _shipperService.GetAllAsync();

            return Ok(new { items = getAllShippers });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Shippers",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Gets a specific Shipper by ID.
    /// </summary>
    /// <param name="id">Shipper ID.</param>
    /// <remarks>
    /// Endpoint that returns a specific Shipper with its linked user account data.
    ///
    /// Possible status codes:
    /// - 200 OK: Shipper found and returned in the response body
    /// - 404 Not Found: no Shipper with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected server error
    /// </remarks>
    /// <returns>Resource containing Shipper and user account information.</returns>
    [HttpGet("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetById(long id)
    {
        try
        {
            var getShipperId = await _shipperService.GetByIdAsync(id);

            return Ok(getShipperId);
        }
        catch (ShipperService.NotFoundException ntex)
        {
            return NotFound(ntex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Shipper",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Registers a new Shipper in the database.
    /// </summary>
    /// <param name="shipperRequestDto">Data of the Shipper and user account to be created.</param>
    /// <remarks>
    /// Public endpoint used to create a Shipper and its linked user account.
    ///
    /// The user account is created first. Then the generated <c>userAccountId</c> is used to link the Shipper to that account.
    ///
    /// The <c>type</c> field must represent the Shipper type according to the application rule, for example <c>PF</c> or <c>PJ</c>.
    ///
    /// Automatically Generated Fields:
    /// - <c>shipperId</c>: generated by the database
    /// - <c>userAccountId</c>: generated by the database
    /// - <c>hashedPassword</c>: the plain password received in the request is hashed before being saved
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "shipperDto": {
    ///         "name": "Cliente Remetente LTDA",
    ///         "shipperDocument": "12345678912345",
    ///         "type": "PJ"
    ///     },
    ///     "userAccountDto": {
    ///         "email": "shipper@email.com",
    ///         "hashedPassword": "Senha123",
    ///         "phone": "11999998888",
    ///         "userRoleId": 1
    ///     }
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 201 Created: Shipper registered successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 409 Conflict: email, document, or other unique information already registered
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while registering the Shipper
    /// </remarks>
    /// <returns>Success message after creating the Shipper.</returns>
    [AllowAnonymous]
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> AddShipper([FromBody] ShipperRequestDTO shipperRequestDto)
    {
        try
        {
            await _shipperService.AddAsync(shipperRequestDto);

            return Created("", new { message = "Shipper added successfully" });
        }
        catch (ShipperService.ConflictException ex)
        {
            return Conflict(ex.Message);
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when adding the Shipper",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Updates the information of an existing Shipper.
    /// </summary>
    /// <param name="id">Shipper ID.</param>
    /// <param name="shipperDto">Shipper data to be updated.</param>
    /// <remarks>
    /// Endpoint that updates only the Shipper registration data.
    /// It does not update the linked user account data.
    ///
    /// The Shipper ID is required only in the route parameter.
    /// If the same information is sent in the request body, the route parameter is used as the main identifier.
    ///
    /// Expected body (JSON):
    /// <code>
    /// {
    ///     "name": "Cliente Remetente Atualizado LTDA",
    ///     "shipperDocument": "98765432112345",
    ///     "type": "PJ"
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: Shipper updated successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 404 Not Found: no Shipper with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while updating the Shipper
    /// </remarks>
    /// <returns>Success message after updating the Shipper.</returns>
    [HttpPut("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateShipper(long id, [FromBody] ShipperDTO shipperDto)
    {
        try
        {
            await _shipperService.UpdateAsync(id, shipperDto);

            return Ok(new { message = $"Shipper with id {id} updated successfully" });
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (ShipperService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when updating the Shipper",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Deletes a Shipper by ID.
    /// </summary>
    /// <param name="id">Shipper ID.</param>
    /// <remarks>
    /// Endpoint used to delete a Shipper registration from the database.
    ///
    /// According to the service rule, the linked user account may also be deleted after deleting the Shipper.
    ///
    /// Possible status codes:
    /// - 200 OK: Shipper deleted successfully
    /// - 404 Not Found: no Shipper with the provided ID was found
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while deleting the Shipper
    /// </remarks>
    /// <returns>Success message after deleting the Shipper.</returns>
    [HttpDelete("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> DeleteShipper(long id)
    {
        try
        {
            await _shipperService.DeleteAsync(id);

            return Ok(new { message = $"Shipper with id {id} deleted" });
        }
        catch (ShipperService.NotFoundException ex)
        {
            return NotFound(ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when deleting the Shipper",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Searches Shippers with optional filters, pagination, and sorting.
    /// </summary>
    /// <param name="name">Shipper name for optional filtering.</param>
    /// <param name="type">Shipper type for optional filtering, for example <c>PF</c> or <c>PJ</c>.</param>
    /// <param name="page">Page number. Default: 1, minimum: 1.</param>
    /// <param name="pageSize">Page size. Default: 10, maximum according to the application rule.</param>
    /// <param name="sortBy">Sorting field. Default: <c>shipperId</c>.</param>
    /// <param name="sortDir">Sorting direction: <c>asc</c> or <c>desc</c>.</param>
    /// <remarks>
    /// Returns Shippers matching the search criteria.
    ///
    /// Example request:
    /// <code>
    /// GET /api/Shipper/search?name=Cliente&amp;type=PJ&amp;page=1&amp;pageSize=10&amp;sortBy=shipperId&amp;sortDir=asc
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: results returned successfully. The list may be empty
    /// - 400 Bad Request: invalid filter, pagination, or sorting parameters
    /// - 401 Unauthorized: authentication token is missing, invalid, or expired
    /// - 500 Internal Server Error: unexpected error while performing the search
    /// </remarks>
    /// <returns>Paginated collection of Shippers with pagination information.</returns>
    [HttpGet("search")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> SearchShipper(
        [FromQuery] string? name,
        [FromQuery] string? type,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 10,
        [FromQuery] string sortBy = "shipperId",
        [FromQuery] string sortDir = "asc")
    {
        try
        {
            var result = await _shipperService.SearchAsync(name, type, page, pageSize, sortBy, sortDir);

            return Ok(new { Items = result.Items, PageInfo = result.PageInfo });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching the Shipper",
                details = ex.Message
            });
        }
    }
}